services:

  db_server:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web_app:
    build:
      context: .
      dockerfile: dockerfile
    image: vipin1705/finance_app_demo:latest
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db_server
    entrypoint: [ "/app/start-server.sh" ]

volumes:
  postgres_data:
