# Generated by Django 5.1.3 on 2024-11-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsManagementApp', '0002_alter_project_description_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('office_supplies', 'Office Supplies'), ('travel', 'Travel'), ('utilities', 'Utilities'), ('salary', 'Salary'), ('miscellaneous', 'Miscellaneous'), ('gst', 'GST'), ('gem', 'GeM'), ('esi', 'ESI')], max_length=15, null=True),
        ),
    ]
