# Generated by Django 5.1.3 on 2024-11-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsManagementApp', '0005_project_end_date_after_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='expense_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='income_expense_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10),
        ),
    ]
