name: FinanceApp CI Dev

on:
  push:
    branches: [ "dev" ]
  # pull_request:
  #   branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to DockerHub
      env:
        DOCKER_USENAME : ${{secrets.DOCKER_USENAME}}
        DOCKER_PASSWORD : ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USENAME -p $DOCKER_PASSWORD

    - name: Build Docker Image
      run: docker build -t finance_app .

    - name: Push to DockerHub
      run : docker push vipin1705/finanace_app:latest
    
      
